import type { Candidate, SelectionProcess, Vacancy } from "../../../src/types/models";

export const demoData = {
  candidates: [
    {
      id: "C-2024-0451",
      fullName: "Maria Gonzalez",
      email: "maria.gonzalez@email.com",
      phone: "+56912345678",
      yearsOfExperience: 5,
      skills: ["TypeScript", "React", "Node.js", "PostgreSQL"],
      englishLevel: "B2" as const,
      seniority: "Semi-Senior" as const,
      currentSalary: 3500,
      expectedSalary: 4200,
      availability: "1 month" as const,
      location: "Valencia, Espana",
      remoteOnly: false,
      status: "Active" as const,
    },
    {
      id: "C-2024-0452",
      fullName: "Juan Perez",
      email: "juan.perez@email.com",
      phone: "+56987654321",
      yearsOfExperience: 3,
      skills: ["JavaScript", "React", "CSS", "HTML"],
      englishLevel: "B1" as const,
      seniority: "Junior" as const,
      currentSalary: 2200,
      expectedSalary: 2800,
      availability: "Immediate" as const,
      location: "Miami, Estados Unidos",
      remoteOnly: true,
      status: "Active" as const,
    },
    {
      id: "C-2024-0453",
      fullName: "Carolina Silva",
      email: "carolina.silva@email.com",
      phone: "+56911223344",
      yearsOfExperience: 8,
      skills: ["TypeScript", "Node.js", "PostgreSQL", "Docker", "AWS"],
      englishLevel: "C1" as const,
      seniority: "Senior" as const,
      currentSalary: 5500,
      expectedSalary: 6500,
      availability: "2 weeks" as const,
      location: "Valencia, Espana",
      remoteOnly: false,
      status: "In process" as const,
    },
  ] satisfies Candidate[],

  vacancy: {
    id: "V-2024-0892",
    title: "Senior Full-Stack Developer",
    companyName: "TechCorp Solutions",
    requiredSkills: ["TypeScript", "React", "Node.js"],
    preferredSkills: ["PostgreSQL", "Docker"],
    minYearsExperience: 4,
    maxYearsExperience: 8,
    requiredEnglishLevel: "B2" as const,
    requiredSeniority: "Senior" as const,
    salaryRangeMin: 5000,
    salaryRangeMax: 7000,
    isRemote: true,
    location: "Remote",
    status: "Open" as const,
  } satisfies Vacancy,

  sampleProcesses: [
    {
      id: "SP-2024-1523",
      candidateId: "C-2024-0451",
      vacancyId: "V-2024-0892",
      stage: "Screening" as const,
      score: 75,
      notes: "Buen perfil, falta experiencia en Docker.",
      createdAt: new Date("2024-06-01T10:00:00Z"),
      updatedAt: new Date("2024-06-01T10:00:00Z"),
    },
    {
      id: "SP-2024-1524",
      candidateId: "C-2024-0452",
      vacancyId: "V-2024-0892",
      stage: "Hired" as const,
      score: 60,
      notes: "Perfil junior con potencial.",
      createdAt: new Date("2024-06-02T11:00:00Z"),
      updatedAt: new Date("2024-06-02T11:00:00Z"),
    },
    {
      id: "SP-2024-1525",
      candidateId: "C-2024-0453",
      vacancyId: "V-2024-0892",
      stage: "Interview" as const,
      score: 85,
      notes: "Excelente match general.",
      createdAt: new Date("2024-06-03T12:00:00Z"),
      updatedAt: new Date("2024-06-03T12:00:00Z"),
    },
  ] satisfies SelectionProcess[],
};